version: "3"

# Modifications and requirements:
# - Removed NGINX, added Treafik in an internet facing HTTPS state
# - Traefik information:
#     - added SSL through HTTPS, requires a domain with a service provider that supporst letsencrypt DNS based HTTPS providers (namecheap in this example)
#     - .env file needs secrets for namecheap / provider of choice, copy .env_example to .env and update
#     - Other providers besides namecheap's varaibles: https://doc.traefik.io/traefik/v2.0/https/acme/#providers
#     - update treafik/traefik.toml with your email address to receive LetsEncrypt expiration warnings
#     - once setup SSL certificate should be automated and auto-renew
# - app/Dockerfile MM version pinned to latest quality release of mattermost https://docs.mattermost.com/administration/changelog.html

services:

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=''
      - POSTGRES_PASSWORD=''
      - POSTGRES_DB=''
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority (link: https://github.com/mattermost/mattermost-server/issues/13059)
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=''
      - MM_PASSWORD=''
      - MM_DBNAME=''

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    labels:
      - "public.https=true"
      - "traefik.http.services.test.loadbalancer.server.port=8000"
      - "traefik.http.routers.test.rule=Host(`mattermost.whateveryourdomainis.com`)"
      - "traefik.http.routers.test.entrypoints=secure"

  traefik:
    image: traefik:v2.2
    container_name: dmz_traefik
    restart: unless-stopped
    domainname: whateveryourdomainis.com
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    dns:
      -  156.154.132.200  # namecheap 1
        -156.154.133.200  # namecheap 2
    environment:
      # REQUIRED FOR HTTPS https://doc.traefik.io/traefik/v2.0/https/acme/#dnschallenge
      # Setup your passwords in .env and empty keys for your provier here
      - NAMECHEAP_API_USER=''
      - NAMECHEAP_API_KEY=''
